version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/test-plugin"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/src/it/test-plugin/src/it/multi-module"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
